/*
 * CreateFolderFrame.java
 *
 * Created on 2008年9月2日, 下午4:26
 */

package com.cdd.fileItem;

import java.io.File;

import javax.swing.JOptionPane;

import com.cdd.uitl.FileHeald;
import com.fileBath.util.MyFileChooser;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class CreateFolderFrame extends javax.swing.JFrame {

    /** Creates new form CreateFolderFrame */
    public CreateFolderFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        messagejLabel = new javax.swing.JLabel();
        pathjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        NamejLabel = new javax.swing.JLabel();
        pathjTextField1 = new javax.swing.JTextField();
        createjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("新建文件夹系列：");
        setTitle("新建文件夹");
        messagejLabel.setText(" 文 件 路 径：");

        jButton1.setText("文件路径");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NamejLabel.setText("  文  件  名：");

        createjButton.setText("创建");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(messagejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(pathjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messagejLabel)
                    .addComponent(pathjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamejLabel)
                    .addComponent(pathjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createjButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    MyFileChooser myfile = new MyFileChooser();
    myfile.getFolder();
    String strPath = myfile.getFolderPath();
    pathjTextField.setText(strPath);
}

private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {
	if( pathjTextField1.getText().equals("")||pathjTextField.getText().equals("")){
		JOptionPane.showMessageDialog(this,"文件名称或地址没有填写完整","信息对话框", JOptionPane.WARNING_MESSAGE);
	 return;
	}
	String strFile = pathjTextField.getText()+"\\"+pathjTextField1.getText();
	File file = new File(strFile);
	if(file.exists()){
		JOptionPane.showMessageDialog(this,"文件夹已存在，请重新换一个文件名","信息对话框", JOptionPane.WARNING_MESSAGE);
		pathjTextField1.setText("");
		return;
	}
	FileHeald fileHeald = new FileHeald();
	fileHeald.createFolder(pathjTextField.getText()+"\\"+pathjTextField1.getText());
	JOptionPane.showMessageDialog(this, "文件夹创建成功", "信息对话框", JOptionPane.WARNING_MESSAGE);

}
    /**
    * @param args the command line arguments
    */
   
    private javax.swing.JLabel NamejLabel;
    private javax.swing.JButton createjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel messagejLabel;
    private javax.swing.JTextField pathjTextField;
    private javax.swing.JTextField pathjTextField1;
}
