/*
 * NewJFrame.java
 *
 * Created on 2008年7月10日, 下午4:22
 */
package com.mwq.stat;

import com.mwq.stat.tool.ScreenSize;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *版权所有：明日科技有限公司
 * @author  Administrator
 */
public class StatFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public StatFrame() {
        initComponents();
        ScreenSize.centered(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        statPanel = new com.mwq.stat.StatPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("决策分析");
        getContentPane().add(statPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StatFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(StatFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(StatFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(StatFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new StatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private com.mwq.stat.StatPanel statPanel;
    // End of variables declaration                   
}
