/*
 * ChartDialog.java
 *
 * Created on 2008年7月21日, 上午8:47
 */
package com.mwq.stat.frame;

import com.mwq.stat.tool.ScreenSize;

/**
 *版权所有：明日科技有限公司
 * @author  Administrator
 */
public class ChartDialog extends javax.swing.JDialog {

    /** Creates new form ChartDialog */
    public ChartDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ScreenSize.centered(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        allRadioButton = new javax.swing.JRadioButton();
        clearRadioButton = new javax.swing.JRadioButton();
        piePanel = new javax.swing.JPanel();
        pieAnalyesCheckBox = new javax.swing.JCheckBox();
        areaPanel = new javax.swing.JPanel();
        areaCollectCheckBox = new javax.swing.JCheckBox();
        areaAnalyesCheckBox = new javax.swing.JCheckBox();
        barPanel = new javax.swing.JPanel();
        barCheckBox = new javax.swing.JCheckBox();
        barCollectCheckBox = new javax.swing.JCheckBox();
        barAnalyesCheckBox = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("包含统计图");
        setResizable(false);

        buttonGroup.add(allRadioButton);
        allRadioButton.setSelected(true);
        allRadioButton.setText("全选");
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(clearRadioButton);
        clearRadioButton.setText("全不选");
        clearRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        piePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("饼型图"));

        pieAnalyesCheckBox.setSelected(true);
        pieAnalyesCheckBox.setText("饼形图分析");

        javax.swing.GroupLayout piePanelLayout = new javax.swing.GroupLayout(piePanel);
        piePanel.setLayout(piePanelLayout);
        piePanelLayout.setHorizontalGroup(
            piePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieAnalyesCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        piePanelLayout.setVerticalGroup(
            piePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieAnalyesCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        areaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("区域图"));

        areaCollectCheckBox.setSelected(true);
        areaCollectCheckBox.setText("区域图汇总");

        areaAnalyesCheckBox.setSelected(true);
        areaAnalyesCheckBox.setText("区域图分析");

        javax.swing.GroupLayout areaPanelLayout = new javax.swing.GroupLayout(areaPanel);
        areaPanel.setLayout(areaPanelLayout);
        areaPanelLayout.setHorizontalGroup(
            areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaCollectCheckBox)
                    .addComponent(areaAnalyesCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        areaPanelLayout.setVerticalGroup(
            areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaCollectCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaAnalyesCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("柱型图"));

        barCheckBox.setSelected(true);
        barCheckBox.setText("柱形图概览");

        barCollectCheckBox.setSelected(true);
        barCollectCheckBox.setText("柱形图汇总");

        barAnalyesCheckBox.setSelected(true);
        barAnalyesCheckBox.setText("柱形图分析");

        javax.swing.GroupLayout barPanelLayout = new javax.swing.GroupLayout(barPanel);
        barPanel.setLayout(barPanelLayout);
        barPanelLayout.setHorizontalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barCheckBox)
                    .addComponent(barCollectCheckBox)
                    .addComponent(barAnalyesCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barPanelLayout.setVerticalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barCollectCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barAnalyesCheckBox)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        submitButton.setText("确定");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(barPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allRadioButton)
                            .addComponent(clearRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
    if (allRadioButton.isSelected()) {
        barCheckBox.setSelected(true);
        barCollectCheckBox.setSelected(true);
        barAnalyesCheckBox.setSelected(true);
        pieAnalyesCheckBox.setSelected(true);
        areaCollectCheckBox.setSelected(true);
        areaAnalyesCheckBox.setSelected(true);
    } else {
        barCheckBox.setSelected(false);
        barCollectCheckBox.setSelected(false);
        barAnalyesCheckBox.setSelected(false);
        pieAnalyesCheckBox.setSelected(false);
        areaCollectCheckBox.setSelected(false);
        areaAnalyesCheckBox.setSelected(false);
    }
}                                           

private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
// TODO add your handling code here:
    setVisible(false);
}                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ChartDialog dialog = new ChartDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.JCheckBox areaAnalyesCheckBox;
    private javax.swing.JCheckBox areaCollectCheckBox;
    private javax.swing.JPanel areaPanel;
    private javax.swing.JCheckBox barAnalyesCheckBox;
    private javax.swing.JCheckBox barCheckBox;
    private javax.swing.JCheckBox barCollectCheckBox;
    private javax.swing.JPanel barPanel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton clearRadioButton;
    private javax.swing.JCheckBox pieAnalyesCheckBox;
    private javax.swing.JPanel piePanel;
    private javax.swing.JButton submitButton;
    // End of variables declaration                   

    public javax.swing.JCheckBox getAreaAnalyesCheckBox() {
        return areaAnalyesCheckBox;
    }

    public javax.swing.JCheckBox getAreaCollectCheckBox() {
        return areaCollectCheckBox;
    }

    public javax.swing.JCheckBox getBarAnalyesCheckBox() {
        return barAnalyesCheckBox;
    }

    public javax.swing.JCheckBox getBarCheckBox() {
        return barCheckBox;
    }

    public javax.swing.JCheckBox getBarCollectCheckBox() {
        return barCollectCheckBox;
    }

    public javax.swing.JCheckBox getPieAnalyesCheckBox() {
        return pieAnalyesCheckBox;
    }
}
