/*
 * UpdateHeadingDialog.java
 *
 * Created on 2008年7月11日, 上午8:58
 */
package com.mwq.stat.frame;

import com.mwq.stat.tool.ScreenSize;
import javax.swing.JLabel;

/**
 *版权所有：明日科技有限公司
 * @author  Administrator
 */
public class UpdateHeadingDialog extends javax.swing.JDialog {

    private JLabel tableHeadingLabel;
    private JLabel tableSubheadingLabel;

    /** Creates new form UpdateHeadingDialog */
    public UpdateHeadingDialog(java.awt.Frame parent, boolean modal, JLabel headingLabel, JLabel subheadingLabel) {
        super(parent, modal);
        this.tableHeadingLabel = headingLabel;
        this.tableSubheadingLabel = subheadingLabel;
        initComponents();
        headingTextField.setText(headingLabel.getText());
        subheadingTextField.setText(subheadingLabel.getText());
        ScreenSize.centered(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        headingTextField = new javax.swing.JTextField();
        subheadingLabel = new javax.swing.JLabel();
        subheadingTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("修改表题");

        headingLabel.setText("主标题：");

        headingTextField.setColumns(30);
        headingTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                headingTextFieldKeyPressed(evt);
            }
        });

        subheadingLabel.setText("副标题：");

        subheadingTextField.setColumns(30);
        subheadingTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subheadingTextFieldKeyPressed(evt);
            }
        });

        exitButton.setText("退出");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        subButton.setText("确定");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(headingLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(headingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(subheadingLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subheadingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingLabel)
                    .addComponent(headingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subheadingLabel)
                    .addComponent(subheadingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(subButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

private void headingTextFieldKeyPressed(java.awt.event.KeyEvent evt) {                                            
// TODO add your handling code here:
    if (headingTextField.getText().trim().length() == 30) {
        evt.consume();
    }
}                                           

private void subheadingTextFieldKeyPressed(java.awt.event.KeyEvent evt) {                                               
// TODO add your handling code here:
    if (subheadingTextField.getText().trim().length() == 30) {
        evt.consume();
    }
}                                              

private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:    
    String heading = headingTextField.getText().trim();
    String subheading = subheadingTextField.getText().trim();
    tableHeadingLabel.setText(heading);
    tableSubheadingLabel.setText(subheading);
    this.dispose();
}                                         

private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
    this.dispose();
}                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UpdateHeadingDialog dialog = new UpdateHeadingDialog(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JTextField headingTextField;
    private javax.swing.JButton subButton;
    private javax.swing.JLabel subheadingLabel;
    private javax.swing.JTextField subheadingTextField;
    // End of variables declaration                   
}
