/*
 * sortFrame.java
 *
 * Created on 2008�?�?8�? 上午8:23
 */

package com.cdd.uitl;

import java.util.List;

import javax.swing.JOptionPane;

import com.fileBath.util.MyFileChooser;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class SortFrame extends javax.swing.JFrame implements Runnable{

    /** Creates new form sortFrame */
    public SortFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fileSort = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        fileShowButton = new javax.swing.JButton();
        statejLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fileSort.setText("文件分类管理");

        messageLabel.setText("分类地址");

        fileShowButton.setText("分类地址");
        fileShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileShowButtonActionPerformed(evt);
            }
        });

        statejLabel.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(fileSort, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileShowButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(statejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(messageLabel)
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fileShowButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fileSort, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(statejLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void fileShowButtonActionPerformed(java.awt.event.ActionEvent evt) {
	MyFileChooser myfile = new MyFileChooser();
	myfile.getFolder();
	String strPath = myfile.getFolderPath();
	pathTextField.setText(strPath);
	int  n = JOptionPane.showConfirmDialog(this, "确定分类地址吗？","确认对话框",JOptionPane.YES_NO_OPTION);
	if(n == JOptionPane.YES_OPTION){
	statejLabel.setText("正在整理文件...");
	Thread thread = new Thread(this);
	thread.start();
	}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileShowButton;
    private javax.swing.JLabel fileSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel statejLabel;
    // End of variables declaration//GEN-END:variables
public void run() {				
	FileHeald fileH = new FileHeald();
	List list = fileH.getList(pathTextField.getText());
     for(int i = 0;i<list.size();i++){
    	 String strFile = list.get(i).toString();
    	 int index = strFile.lastIndexOf(".");
    	 if(index != -1){
    		 String strN = strFile.substring(index+1,strFile.length());
    		 int ind = strFile.lastIndexOf("\\");
    		 String strFileName = strFile.substring(ind, index);
    		 fileH.createFolder(pathTextField.getText()+"\\"+"分类");
    		 fileH.createFolder(pathTextField.getText()+"\\"+"分类"+"\\"+strN);
    		 if(strFile.endsWith(strN)){
    			 fileH.copyFile(strFile,pathTextField.getText()+"\\"+"分类"+"\\"+strN+
    					 "\\"+strFileName+strFile.substring(index,strFile.length()));
    		 }
    		 statejLabel.setText("文件分类结束");
    	 }
     }
}

}
