/*
 * FileNameCopyBatch.java
 *
 * Created on 2008�?�?8�? 上午10:23
 */

package com.cdd.editItem;

import java.io.File;

import javax.swing.JOptionPane;

import com.cdd.uitl.FileHeald;
import com.fileBath.util.MyFileChooser;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class FileNameremoveBatch extends javax.swing.JFrame implements Runnable {

    /** Creates new form FileNameCopyBatch */
    public FileNameremoveBatch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        FilePatchLabel = new javax.swing.JLabel();
        FileTextField = new javax.swing.JTextField();
        choiceButton = new javax.swing.JButton();
        FileSaveLabel = new javax.swing.JLabel();
        FileSaveTextField = new javax.swing.JTextField();
        choiceSaveButton = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        copyjButton = new javax.swing.JButton();
        stateLabel = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        titleLabel.setText("移动文件夹中的指定文件：");
        FilePatchLabel.setText("文件地址");
        choiceButton.setText("选择");
        choiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceButtonActionPerformed(evt);
            }
        });

        FileSaveLabel.setText("移动地址");

        choiceSaveButton.setText("选择");
        choiceSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceSaveButtonActionPerformed(evt);
            }
        });

        fileName.setText("文件扩展名：");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".doc", ".txt", ".zip", ".jpg",".rar" }));

        copyjButton.setText("移动");
        copyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyjButtonActionPerformed(evt);
            }
        });
        stateLabel.setText("");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FilePatchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choiceButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(copyjButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(FileSaveLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FileSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(choiceSaveButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilePatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileSaveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileSaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceSaveButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(copyjButton))
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(stateLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceButtonActionPerformed
    	MyFileChooser myfile = new MyFileChooser();
    	myfile.getFolder();
    	String strPath = myfile.getFolderPath();
    	FileTextField.setText(strPath);
    	
    }

    private void choiceSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceSaveButtonActionPerformed
    	MyFileChooser myfile = new MyFileChooser();
    	myfile.getFolder();
    	String strPath = myfile.getFolderPath();
    	FileSaveTextField.setText(strPath);
    }

private void copyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyjButtonActionPerformed
	if((FileTextField.getText().equals("")) ||(FileSaveTextField.getText().equals(""))){
		JOptionPane.showMessageDialog(this,"没有将文件地址添��写完�","信息对话�",JOptionPane.WARNING_MESSAGE);
		return;
	}
	Thread thread = new Thread(this);
	thread.start();
}

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FilePatchLabel;
    private javax.swing.JLabel FileSaveLabel;
    private javax.swing.JTextField FileSaveTextField;
    private javax.swing.JTextField FileTextField;
    private javax.swing.JButton choiceButton;
    private javax.swing.JButton choiceSaveButton;
    private javax.swing.JButton copyjButton;
    private javax.swing.JLabel fileName;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
public void run() {
	FileHeald fileHeald = new FileHeald();
	java.util.List list = fileHeald.getList(FileTextField.getText());
	if(!list.isEmpty()){
		MyRemoveMessage myRemoveMessage = new MyRemoveMessage();
		myRemoveMessage.setVisible(true);
		for(int i = 0 ;i<list.size();i++){
			String strFileName = list.get(i).toString();
			if(strFileName.endsWith(jComboBox1.getSelectedItem().toString())){
				int index = strFileName.lastIndexOf("\\");				
				String strNewName = strFileName.substring(index+1,strFileName.length());
				fileHeald.copyFile(strFileName, FileSaveTextField.getText()+"\\"+strNewName); 
				File file = new File(strFileName);
				file.delete();    				
			}
		}
		myRemoveMessage.setVisible(false);
		JOptionPane.showMessageDialog(this, "文件移动完毕", "信息对话框", JOptionPane.WARNING_MESSAGE);
	}
	if(list.isEmpty()){
		JOptionPane.showMessageDialog(this, "文件夹为空", "消息对话框",JOptionPane.WARNING_MESSAGE);
	}		
}

}
