/*
 * AlignPanel.java
 *
 * Created on 2008年7月24日, 下午12:57
 */
package com.mwq.print.tabbedPane;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class AlignPanel extends javax.swing.JPanel {

    /** Creates new form AlignPanel */
    public AlignPanel() {
        initComponents();
        zoomRadioButtonActionPerformed(null);
        minRadioButtonActionPerformed(null);
        maxRadioButtonActionPerformed(null);
        fillRadioButton.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        zoomButtonGroup = new javax.swing.ButtonGroup();
        minButtonGroup = new javax.swing.ButtonGroup();
        maxButtonGroup = new javax.swing.ButtonGroup();
        hButtonGroup = new javax.swing.ButtonGroup();
        vButtonGroup = new javax.swing.ButtonGroup();
        zoomPanel = new javax.swing.JPanel();
        defaultRadioButton = new javax.swing.JRadioButton();
        fillRadioButton = new javax.swing.JRadioButton();
        setRadioButton = new javax.swing.JRadioButton();
        minPanel = new javax.swing.JPanel();
        minDefaultRadioButton = new javax.swing.JRadioButton();
        minFillRadioButton = new javax.swing.JRadioButton();
        minSetRadioButton = new javax.swing.JRadioButton();
        minPresentLabel = new javax.swing.JLabel();
        minPresentComboBox = new javax.swing.JComboBox();
        maxPanel = new javax.swing.JPanel();
        maxDefaultRadioButton = new javax.swing.JRadioButton();
        maxFillRadioButton = new javax.swing.JRadioButton();
        maxSetRadioButton = new javax.swing.JRadioButton();
        maxPresentLabel = new javax.swing.JLabel();
        maxPresentComboBox = new javax.swing.JComboBox();
        alignPanel = new javax.swing.JPanel();
        horizontalPanel = new javax.swing.JPanel();
        hLeftRadioButton = new javax.swing.JRadioButton();
        hCenterRadioButton = new javax.swing.JRadioButton();
        hRightRadioButton = new javax.swing.JRadioButton();
        verticalPanel = new javax.swing.JPanel();
        vUpRadioButton = new javax.swing.JRadioButton();
        vCenterRadioButton = new javax.swing.JRadioButton();
        vDownRadioButton = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        zoomPanel.setBackground(new java.awt.Color(255, 255, 255));
        zoomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("缩放"));

        defaultRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        zoomButtonGroup.add(defaultRadioButton);
        defaultRadioButton.setSelected(true);
        defaultRadioButton.setText("默认");
        defaultRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomRadioButtonActionPerformed(evt);
            }
        });

        fillRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        zoomButtonGroup.add(fillRadioButton);
        fillRadioButton.setText("充满");
        fillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomRadioButtonActionPerformed(evt);
            }
        });

        setRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        zoomButtonGroup.add(setRadioButton);
        setRadioButton.setText("自定义");
        setRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomRadioButtonActionPerformed(evt);
            }
        });

        minPanel.setBackground(new java.awt.Color(255, 255, 255));
        minPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("小"));

        minDefaultRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        minButtonGroup.add(minDefaultRadioButton);
        minDefaultRadioButton.setSelected(true);
        minDefaultRadioButton.setText("默认");
        minDefaultRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRadioButtonActionPerformed(evt);
            }
        });

        minFillRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        minButtonGroup.add(minFillRadioButton);
        minFillRadioButton.setText("充满");
        minFillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRadioButtonActionPerformed(evt);
            }
        });

        minSetRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        minButtonGroup.add(minSetRadioButton);
        minSetRadioButton.setText("自定义");
        minSetRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRadioButtonActionPerformed(evt);
            }
        });

        minPresentLabel.setText("放大比例：");

        minPresentComboBox.setMaximumRowCount(9);
        minPresentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%" }));

        javax.swing.GroupLayout minPanelLayout = new javax.swing.GroupLayout(minPanel);
        minPanel.setLayout(minPanelLayout);
        minPanelLayout.setHorizontalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(minPanelLayout.createSequentialGroup()
                        .addComponent(minDefaultRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minFillRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minSetRadioButton))
                    .addGroup(minPanelLayout.createSequentialGroup()
                        .addComponent(minPresentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minPresentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        minPanelLayout.setVerticalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minDefaultRadioButton)
                    .addComponent(minFillRadioButton)
                    .addComponent(minSetRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minPresentLabel)
                    .addComponent(minPresentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        maxPanel.setBackground(new java.awt.Color(255, 255, 255));
        maxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("大"));

        maxDefaultRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        maxButtonGroup.add(maxDefaultRadioButton);
        maxDefaultRadioButton.setText("默认");
        maxDefaultRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxRadioButtonActionPerformed(evt);
            }
        });

        maxFillRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        maxButtonGroup.add(maxFillRadioButton);
        maxFillRadioButton.setSelected(true);
        maxFillRadioButton.setText("充满");
        maxFillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxRadioButtonActionPerformed(evt);
            }
        });

        maxSetRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        maxButtonGroup.add(maxSetRadioButton);
        maxSetRadioButton.setText("自定义");
        maxSetRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxRadioButtonActionPerformed(evt);
            }
        });

        maxPresentLabel.setText("缩小比例：");

        maxPresentComboBox.setMaximumRowCount(9);
        maxPresentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%" }));

        javax.swing.GroupLayout maxPanelLayout = new javax.swing.GroupLayout(maxPanel);
        maxPanel.setLayout(maxPanelLayout);
        maxPanelLayout.setHorizontalGroup(
            maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maxPanelLayout.createSequentialGroup()
                        .addComponent(maxDefaultRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxFillRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxSetRadioButton))
                    .addGroup(maxPanelLayout.createSequentialGroup()
                        .addComponent(maxPresentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxPresentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maxPanelLayout.setVerticalGroup(
            maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDefaultRadioButton)
                    .addComponent(maxFillRadioButton)
                    .addComponent(maxSetRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPresentLabel)
                    .addComponent(maxPresentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout zoomPanelLayout = new javax.swing.GroupLayout(zoomPanel);
        zoomPanel.setLayout(zoomPanelLayout);
        zoomPanelLayout.setHorizontalGroup(
            zoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zoomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maxPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, zoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(zoomPanelLayout.createSequentialGroup()
                            .addComponent(defaultRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fillRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(setRadioButton))
                        .addComponent(minPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        zoomPanelLayout.setVerticalGroup(
            zoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zoomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultRadioButton)
                    .addComponent(fillRadioButton)
                    .addComponent(setRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alignPanel.setBackground(new java.awt.Color(255, 255, 255));
        alignPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("对齐"));

        horizontalPanel.setBackground(new java.awt.Color(255, 255, 255));
        horizontalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("水平"));

        hLeftRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hButtonGroup.add(hLeftRadioButton);
        hLeftRadioButton.setText("左对齐");
        hLeftRadioButton.setName("2"); // NOI18N

        hCenterRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hButtonGroup.add(hCenterRadioButton);
        hCenterRadioButton.setSelected(true);
        hCenterRadioButton.setText("居中");
        hCenterRadioButton.setName("0"); // NOI18N

        hRightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hButtonGroup.add(hRightRadioButton);
        hRightRadioButton.setText("右对齐");
        hRightRadioButton.setName("4"); // NOI18N

        javax.swing.GroupLayout horizontalPanelLayout = new javax.swing.GroupLayout(horizontalPanel);
        horizontalPanel.setLayout(horizontalPanelLayout);
        horizontalPanelLayout.setHorizontalGroup(
            horizontalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horizontalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(horizontalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hLeftRadioButton)
                    .addComponent(hCenterRadioButton)
                    .addComponent(hRightRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        horizontalPanelLayout.setVerticalGroup(
            horizontalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horizontalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hLeftRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hCenterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hRightRadioButton))
        );

        verticalPanel.setBackground(new java.awt.Color(255, 255, 255));
        verticalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("垂直"));

        vUpRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        vButtonGroup.add(vUpRadioButton);
        vUpRadioButton.setText("上对齐");
        vUpRadioButton.setName("1"); // NOI18N

        vCenterRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        vButtonGroup.add(vCenterRadioButton);
        vCenterRadioButton.setSelected(true);
        vCenterRadioButton.setText("居中");
        vCenterRadioButton.setName("0"); // NOI18N

        vDownRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        vButtonGroup.add(vDownRadioButton);
        vDownRadioButton.setText("下对齐");
        vDownRadioButton.setName("3"); // NOI18N

        javax.swing.GroupLayout verticalPanelLayout = new javax.swing.GroupLayout(verticalPanel);
        verticalPanel.setLayout(verticalPanelLayout);
        verticalPanelLayout.setHorizontalGroup(
            verticalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verticalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verticalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vUpRadioButton)
                    .addComponent(vCenterRadioButton)
                    .addComponent(vDownRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verticalPanelLayout.setVerticalGroup(
            verticalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verticalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vUpRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vCenterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vDownRadioButton))
        );

        javax.swing.GroupLayout alignPanelLayout = new javax.swing.GroupLayout(alignPanel);
        alignPanel.setLayout(alignPanelLayout);
        alignPanelLayout.setHorizontalGroup(
            alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horizontalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(verticalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alignPanelLayout.setVerticalGroup(
            alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verticalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horizontalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(alignPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zoomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

private void zoomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO add your handling code here:
    if (setRadioButton.isSelected()) {
        minDefaultRadioButton.setEnabled(true);
        minFillRadioButton.setEnabled(true);
        minSetRadioButton.setEnabled(true);
        if (minSetRadioButton.isSelected()) {
            minPresentLabel.setEnabled(true);
            minPresentComboBox.setEnabled(true);
        }

        maxDefaultRadioButton.setEnabled(true);
        maxFillRadioButton.setEnabled(true);
        maxSetRadioButton.setEnabled(true);
        if (maxSetRadioButton.isSelected()) {
            maxPresentLabel.setEnabled(true);
            maxPresentComboBox.setEnabled(true);
        }
    } else {
        minDefaultRadioButton.setEnabled(false);
        minFillRadioButton.setEnabled(false);
        minSetRadioButton.setEnabled(false);
        if (minSetRadioButton.isSelected()) {
            minPresentLabel.setEnabled(false);
            minPresentComboBox.setEnabled(false);
        }

        maxDefaultRadioButton.setEnabled(false);
        maxFillRadioButton.setEnabled(false);
        maxSetRadioButton.setEnabled(false);
        if (maxSetRadioButton.isSelected()) {
            maxPresentLabel.setEnabled(false);
            maxPresentComboBox.setEnabled(false);
        }
    }
}                                               

private void minRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    if (minSetRadioButton.isSelected()) {
        minPresentLabel.setEnabled(true);
        minPresentComboBox.setEnabled(true);
    } else {
        minPresentLabel.setEnabled(false);
        minPresentComboBox.setEnabled(false);
    }
}                                              

private void maxRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    if (maxSetRadioButton.isSelected()) {
        maxPresentLabel.setEnabled(true);
        maxPresentComboBox.setEnabled(true);
    } else {
        maxPresentLabel.setEnabled(false);
        maxPresentComboBox.setEnabled(false);
    }
}                                              

    // Variables declaration - do not modify                     
    private javax.swing.JPanel alignPanel;
    private javax.swing.JRadioButton defaultRadioButton;
    private javax.swing.JRadioButton fillRadioButton;
    private javax.swing.ButtonGroup hButtonGroup;
    private javax.swing.JRadioButton hCenterRadioButton;
    private javax.swing.JRadioButton hLeftRadioButton;
    private javax.swing.JRadioButton hRightRadioButton;
    private javax.swing.JPanel horizontalPanel;
    private javax.swing.ButtonGroup maxButtonGroup;
    private javax.swing.JRadioButton maxDefaultRadioButton;
    private javax.swing.JRadioButton maxFillRadioButton;
    private javax.swing.JPanel maxPanel;
    private javax.swing.JComboBox maxPresentComboBox;
    private javax.swing.JLabel maxPresentLabel;
    private javax.swing.JRadioButton maxSetRadioButton;
    private javax.swing.ButtonGroup minButtonGroup;
    private javax.swing.JRadioButton minDefaultRadioButton;
    private javax.swing.JRadioButton minFillRadioButton;
    private javax.swing.JPanel minPanel;
    private javax.swing.JComboBox minPresentComboBox;
    private javax.swing.JLabel minPresentLabel;
    private javax.swing.JRadioButton minSetRadioButton;
    private javax.swing.JRadioButton setRadioButton;
    private javax.swing.ButtonGroup vButtonGroup;
    private javax.swing.JRadioButton vCenterRadioButton;
    private javax.swing.JRadioButton vDownRadioButton;
    private javax.swing.JRadioButton vUpRadioButton;
    private javax.swing.JPanel verticalPanel;
    private javax.swing.ButtonGroup zoomButtonGroup;
    private javax.swing.JPanel zoomPanel;
    // End of variables declaration                   

    public java.util.Enumeration getZoomEnumeration() {
        return zoomButtonGroup.getElements();
    }

    public java.util.Enumeration getMinEnumeration() {
        return minButtonGroup.getElements();
    }

    public java.util.Enumeration getMaxEnumeration() {
        return maxButtonGroup.getElements();
    }

    public java.util.Enumeration getHEnumeration() {
        return hButtonGroup.getElements();
    }

    public java.util.Enumeration getVEnumeration() {
        return vButtonGroup.getElements();
    }

    public float getMaxPresent() {
        return (9 - maxPresentComboBox.getSelectedIndex()) / 10F;
    }

    public float getMinPresent() {
        return (9 - minPresentComboBox.getSelectedIndex()) / 10F + 1;
    }
}
