/*
 * BackPanel.java
 *
 * Created on 2008年7月24日, 下午1:45
 */
package com.mwq.print.tabbedPane;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class BackPanel extends javax.swing.JPanel {

    private boolean hasFocus = false;

    /** Creates new form BackPanel */
    public BackPanel() {
        initComponents();
        addRadioButtonActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addButtonGroup = new javax.swing.ButtonGroup();
        alignButtonGroup = new javax.swing.ButtonGroup();
        addLabel = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        photoLabel = new javax.swing.JLabel();
        photoTextField = new javax.swing.JTextField();
        photoButton = new javax.swing.JButton();
        alignLabel = new javax.swing.JLabel();
        defaultRadioButton = new javax.swing.JRadioButton();
        fillRadioButton = new javax.swing.JRadioButton();
        opaqueLabel = new javax.swing.JLabel();
        opaqueSlider = new javax.swing.JSlider();

        setBackground(new java.awt.Color(255, 255, 255));

        addLabel.setText("添加：");

        yesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        addButtonGroup.add(yesRadioButton);
        yesRadioButton.setText("是");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        addButtonGroup.add(noRadioButton);
        noRadioButton.setSelected(true);
        noRadioButton.setText("否");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        photoLabel.setText("图片：");

        photoTextField.setColumns(20);
        photoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                photoTextFieldKeyTyped(evt);
            }
        });

        photoButton.setText("...");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        alignLabel.setText("位置：");

        defaultRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        alignButtonGroup.add(defaultRadioButton);
        defaultRadioButton.setSelected(true);
        defaultRadioButton.setText("默认");

        fillRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        alignButtonGroup.add(fillRadioButton);
        fillRadioButton.setText("充满");

        opaqueLabel.setText("浓度：");

        opaqueSlider.setBackground(new java.awt.Color(255, 255, 255));
        opaqueSlider.setMajorTickSpacing(10);
        opaqueSlider.setMaximum(95);
        opaqueSlider.setMinimum(5);
        opaqueSlider.setMinorTickSpacing(5);
        opaqueSlider.setPaintTicks(true);
        opaqueSlider.setSnapToTicks(true);
        opaqueSlider.setValue(45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesRadioButton)
                        .addGap(30, 30, 30)
                        .addComponent(noRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alignLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(fillRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opaqueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opaqueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLabel)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alignLabel)
                    .addComponent(defaultRadioButton)
                    .addComponent(fillRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opaqueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opaqueLabel)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

private void addRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    boolean enabled = (yesRadioButton.isSelected() ? true : false);
    photoLabel.setEnabled(enabled);
    photoTextField.setEnabled(enabled);
    photoButton.setEnabled(enabled);
    alignLabel.setEnabled(enabled);
    defaultRadioButton.setEnabled(enabled);
    fillRadioButton.setEnabled(enabled);
    opaqueLabel.setEnabled(enabled);
    opaqueSlider.setEnabled(enabled);
    if (enabled) {
        photoTextField.requestFocus();
    }
}                                              

private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new FileFilter() {

        private final String types = ".jpg；.jpeg；.gif";

        @Override
        public boolean accept(File file) {
            if (file.isDirectory()) {
                return true;
            } else {
                String name = file.getName().toLowerCase();
                String type = name.substring(name.lastIndexOf('.'));
                if (types.contains(type)) {
                    return true;
                } else {
                    return false;
                }
            }
        }

        @Override
        public String getDescription() {
            return "图片格式（" + types + "）";
        }
    });
    int showOpenDialog = fileChooser.showOpenDialog(this);
    if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
        photoTextField.setText(fileChooser.getSelectedFile().getPath());
    }
}                                           

private void photoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {                                        
// TODO add your handling code here:
    evt.consume();
}                                       

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup addButtonGroup;
    private javax.swing.JLabel addLabel;
    private javax.swing.ButtonGroup alignButtonGroup;
    private javax.swing.JLabel alignLabel;
    private javax.swing.JRadioButton defaultRadioButton;
    private javax.swing.JRadioButton fillRadioButton;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JLabel opaqueLabel;
    private javax.swing.JSlider opaqueSlider;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration                   

    public boolean isDefault() {
        return defaultRadioButton.isSelected();
    }

    public int getOpaqueValue() {
        return opaqueSlider.getValue();
    }

    public String getPhotoPath() {
        return photoTextField.getText();
    }

    public boolean isAddBackground() {
        return yesRadioButton.isSelected();
    }
}
