/*
 * PagePanel.java
 *
 * Created on 2008年7月24日, 上午11:27
 */
package com.mwq.print.tabbedPane;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class PagePanel extends javax.swing.JPanel {

    /** Creates new form PagePanel */
    public PagePanel() {
        initComponents();
        alignRadioButtonActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pageButtonGroup = new javax.swing.ButtonGroup();
        areaButtonGroup = new javax.swing.ButtonGroup();
        hAlignButtonGroup = new javax.swing.ButtonGroup();
        vAlignButtonGroup = new javax.swing.ButtonGroup();
        addLabel = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        alignPanel = new javax.swing.JPanel();
        alignUpRadioButton = new javax.swing.JRadioButton();
        alignDownRadioButton = new javax.swing.JRadioButton();
        alignLeftRadioButton = new javax.swing.JRadioButton();
        alignRightRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        vCenterRadioButton = new javax.swing.JRadioButton();
        vRightRadioButton = new javax.swing.JRadioButton();
        vLeftRadioButton = new javax.swing.JRadioButton();
        hUpRadioButton = new javax.swing.JRadioButton();
        hCenterRadioButton = new javax.swing.JRadioButton();
        hDownRadioButton = new javax.swing.JRadioButton();
        formatPanel = new javax.swing.JPanel();
        beforeTextField = new javax.swing.JTextField();
        pageNumLabel = new javax.swing.JLabel();
        afterTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        addLabel.setText("打印页码：");

        yesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        pageButtonGroup.add(yesRadioButton);
        yesRadioButton.setSelected(true);
        yesRadioButton.setText("是");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        pageButtonGroup.add(noRadioButton);
        noRadioButton.setText("否");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        alignPanel.setBackground(new java.awt.Color(255, 255, 255));
        alignPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("打印位置"));

        alignUpRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(alignUpRadioButton);
        alignUpRadioButton.setText("页眉");
        alignUpRadioButton.setFocusPainted(false);
        alignUpRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignRadioButtonActionPerformed(evt);
            }
        });

        alignDownRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(alignDownRadioButton);
        alignDownRadioButton.setSelected(true);
        alignDownRadioButton.setText("页脚");
        alignDownRadioButton.setFocusPainted(false);
        alignDownRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignRadioButtonActionPerformed(evt);
            }
        });

        alignLeftRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(alignLeftRadioButton);
        alignLeftRadioButton.setText("左侧");
        alignLeftRadioButton.setFocusPainted(false);
        alignLeftRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignRadioButtonActionPerformed(evt);
            }
        });

        alignRightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(alignRightRadioButton);
        alignRightRadioButton.setText("右侧");
        alignRightRadioButton.setFocusPainted(false);
        alignRightRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alignPanelLayout = new javax.swing.GroupLayout(alignPanel);
        alignPanel.setLayout(alignPanelLayout);
        alignPanelLayout.setHorizontalGroup(
            alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alignUpRadioButton)
                    .addComponent(alignDownRadioButton))
                .addGap(50, 50, 50)
                .addGroup(alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alignRightRadioButton)
                    .addComponent(alignLeftRadioButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        alignPanelLayout.setVerticalGroup(
            alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alignPanelLayout.createSequentialGroup()
                        .addComponent(alignLeftRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alignRightRadioButton))
                    .addGroup(alignPanelLayout.createSequentialGroup()
                        .addComponent(alignUpRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alignDownRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("对齐方式"));

        vCenterRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hAlignButtonGroup.add(vCenterRadioButton);
        vCenterRadioButton.setText("居中");
        vCenterRadioButton.setName("0"); // NOI18N

        vRightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hAlignButtonGroup.add(vRightRadioButton);
        vRightRadioButton.setSelected(true);
        vRightRadioButton.setText("右对齐");
        vRightRadioButton.setName("4"); // NOI18N

        vLeftRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hAlignButtonGroup.add(vLeftRadioButton);
        vLeftRadioButton.setText("左对齐");
        vLeftRadioButton.setName("2"); // NOI18N

        hUpRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        vAlignButtonGroup.add(hUpRadioButton);
        hUpRadioButton.setText("上对齐");
        hUpRadioButton.setName("1"); // NOI18N

        hCenterRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        vAlignButtonGroup.add(hCenterRadioButton);
        hCenterRadioButton.setText("居中");
        hCenterRadioButton.setName("0"); // NOI18N

        hDownRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        vAlignButtonGroup.add(hDownRadioButton);
        hDownRadioButton.setSelected(true);
        hDownRadioButton.setText("下对齐");
        hDownRadioButton.setName("3"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLeftRadioButton)
                    .addComponent(vCenterRadioButton)
                    .addComponent(vRightRadioButton))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hUpRadioButton)
                    .addComponent(hCenterRadioButton)
                    .addComponent(hDownRadioButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hUpRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hCenterRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hDownRadioButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(vLeftRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vCenterRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vRightRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formatPanel.setBackground(new java.awt.Color(255, 255, 255));
        formatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("输出样式"));

        beforeTextField.setColumns(12);
        beforeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beforeTextField.setText("- ");

        pageNumLabel.setText("1");

        afterTextField.setColumns(12);
        afterTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        afterTextField.setText(" -");

        javax.swing.GroupLayout formatPanelLayout = new javax.swing.GroupLayout(formatPanel);
        formatPanel.setLayout(formatPanelLayout);
        formatPanelLayout.setHorizontalGroup(
            formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beforeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        formatPanelLayout.setVerticalGroup(
            formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beforeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageNumLabel)
                    .addComponent(afterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(noRadioButton))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formatPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alignPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLabel)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

private void alignRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
// TODO add your handling code here:
    if (alignUpRadioButton.isSelected() || alignDownRadioButton.isSelected()) {
        vLeftRadioButton.setEnabled(true);
        vCenterRadioButton.setEnabled(true);
        vRightRadioButton.setEnabled(true);

        hUpRadioButton.setEnabled(false);
        hCenterRadioButton.setEnabled(false);
        hDownRadioButton.setEnabled(false);
    } else {
        vLeftRadioButton.setEnabled(false);
        vCenterRadioButton.setEnabled(false);
        vRightRadioButton.setEnabled(false);

        hUpRadioButton.setEnabled(true);
        hCenterRadioButton.setEnabled(true);
        hDownRadioButton.setEnabled(true);
    }
}                                                

private void addRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    boolean enabled = (yesRadioButton.isSelected() ? true : false);
    alignUpRadioButton.setEnabled(enabled);
    alignDownRadioButton.setEnabled(enabled);
    alignLeftRadioButton.setEnabled(enabled);
    alignRightRadioButton.setEnabled(enabled);

    if (enabled) {
        alignRadioButtonActionPerformed(null);
    } else {
        hUpRadioButton.setEnabled(enabled);
        hCenterRadioButton.setEnabled(enabled);
        hDownRadioButton.setEnabled(enabled);
        vLeftRadioButton.setEnabled(enabled);
        vCenterRadioButton.setEnabled(enabled);
        vRightRadioButton.setEnabled(enabled);
    }

    beforeTextField.setEnabled(enabled);
    pageNumLabel.setEnabled(enabled);
    afterTextField.setEnabled(enabled);
}                                              

    // Variables declaration - do not modify                     
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField afterTextField;
    private javax.swing.JRadioButton alignDownRadioButton;
    private javax.swing.JRadioButton alignLeftRadioButton;
    private javax.swing.JPanel alignPanel;
    private javax.swing.JRadioButton alignRightRadioButton;
    private javax.swing.JRadioButton alignUpRadioButton;
    private javax.swing.ButtonGroup areaButtonGroup;
    private javax.swing.JTextField beforeTextField;
    private javax.swing.JPanel formatPanel;
    private javax.swing.ButtonGroup hAlignButtonGroup;
    private javax.swing.JRadioButton hCenterRadioButton;
    private javax.swing.JRadioButton hDownRadioButton;
    private javax.swing.JRadioButton hUpRadioButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.ButtonGroup pageButtonGroup;
    private javax.swing.JLabel pageNumLabel;
    private javax.swing.ButtonGroup vAlignButtonGroup;
    private javax.swing.JRadioButton vCenterRadioButton;
    private javax.swing.JRadioButton vLeftRadioButton;
    private javax.swing.JRadioButton vRightRadioButton;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration                   

    public boolean isAddPage() {
        return yesRadioButton.isSelected();
    }

    public javax.swing.ButtonGroup getHAlignButtonGroup() {
        return hAlignButtonGroup;
    }

    public javax.swing.ButtonGroup getVAlignButtonGroup() {
        return vAlignButtonGroup;
    }

    public javax.swing.ButtonGroup getAreaButtonGroup() {
        return areaButtonGroup;
    }

    public String getBeforeText() {
        return beforeTextField.getText();
    }

    public String getAfterText() {
        return afterTextField.getText();
    }
}
