/*
 * PrintPanel.java
 *
 * Created on 2008年8月1日, 下午2:26
 */
package com.mwq.print.tabbedPane;

import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner.NumberEditor;
import javax.swing.text.NumberFormatter;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class PrintPanel extends javax.swing.JPanel {

    /** Creates new form PrintPanel */
    public PrintPanel() {
        initComponents();
        radioButtonActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        modeButtonGroup = new javax.swing.ButtonGroup();
        orderButtonGroup = new javax.swing.ButtonGroup();
        shareLabel = new javax.swing.JLabel();
        shareSpinner = new javax.swing.JSpinner();
        modeLabel = new javax.swing.JLabel();
        shareRadioButton = new javax.swing.JRadioButton();
        pageRadioButton = new javax.swing.JRadioButton();
        orderLabel = new javax.swing.JLabel();
        forehandRadioButton = new javax.swing.JRadioButton();
        backhanderRadioButton = new javax.swing.JRadioButton();
        layOutLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        shareLabel.setText("打印份数：");

        shareSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99999, 1));
        NumberEditor editor = (NumberEditor) shareSpinner.getEditor();
        JFormattedTextField textField = editor.getTextField();
        NumberFormatter formatter = (NumberFormatter) textField.getFormatter();
        formatter.setAllowsInvalid(false);

        modeLabel.setText("打印模式：");

        shareRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        modeButtonGroup.add(shareRadioButton);
        shareRadioButton.setSelected(true);
        shareRadioButton.setText("逐份打印");
        shareRadioButton.setFocusPainted(false);
        shareRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        pageRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        modeButtonGroup.add(pageRadioButton);
        pageRadioButton.setText("逐页打印");
        pageRadioButton.setFocusPainted(false);
        pageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        orderLabel.setText("打印顺序：");

        forehandRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        orderButtonGroup.add(forehandRadioButton);
        forehandRadioButton.setSelected(true);
        forehandRadioButton.setText("顺序打印");
        forehandRadioButton.setFocusPainted(false);
        forehandRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        backhanderRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        orderButtonGroup.add(backhanderRadioButton);
        backhanderRadioButton.setText("逆序打印");
        backhanderRadioButton.setFocusPainted(false);
        backhanderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        layOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forehandRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(backhanderRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(shareLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shareSpinner))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(modeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shareRadioButton)))
                        .addGap(18, 18, 18)
                        .addComponent(pageRadioButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shareLabel)
                    .addComponent(shareSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeLabel)
                    .addComponent(shareRadioButton)
                    .addComponent(pageRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderLabel)
                    .addComponent(forehandRadioButton)
                    .addComponent(backhanderRadioButton))
                .addGap(18, 18, 18)
                .addComponent(layOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
    String mode = "Share";// 默认为逐份打印
    String order = "Forehand";// 默认为顺序打印
    if (pageRadioButton.isSelected()) {// 采用逐页打印
        mode = "Page";
    }
    if (backhanderRadioButton.isSelected()) {// 采用倒序打印
        order = "Backhander";
    }
    layOutLabel.setName(mode + order);
    String URI = "/img/print/" + layOutLabel.getName() + ".png";// 组织展示图片路径
    layOutLabel.setIcon(new ImageIcon(getClass().getResource(URI)));// 设置展示图片
}                                           

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton backhanderRadioButton;
    private javax.swing.JRadioButton forehandRadioButton;
    private javax.swing.JLabel layOutLabel;
    private javax.swing.ButtonGroup modeButtonGroup;
    private javax.swing.JLabel modeLabel;
    private javax.swing.ButtonGroup orderButtonGroup;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JRadioButton pageRadioButton;
    private javax.swing.JLabel shareLabel;
    private javax.swing.JRadioButton shareRadioButton;
    private javax.swing.JSpinner shareSpinner;
    // End of variables declaration                   

    public String getBluePrint() {
        return layOutLabel.getName();
    }

    public int getPrintShare() {
        return (Integer) shareSpinner.getValue();
    }
}
