/*
 * WaterPanel.java
 *
 * Created on 2008年7月24日, 下午1:18
 */
package com.mwq.print.tabbedPane;

import com.mwq.print.mwing.WatermarkLabel;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JColorChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner.NumberEditor;
import javax.swing.text.NumberFormatter;

/**
 *版权所有：明日科技有限公司
 * @author Administrator
 */
public class WaterPanel extends javax.swing.JPanel {

    /** Creates new form WaterPanel */
    public WaterPanel() {
        initComponents();
        addRadioButtonActionPerformed(null);
    }
    WatermarkLabel watermarkLabel;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        waterButtonGroup = new javax.swing.ButtonGroup();
        pieButtonGroup = new javax.swing.ButtonGroup();
        areaButtonGroup = new javax.swing.ButtonGroup();
        addLabel = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        waterLabel = new javax.swing.JLabel();
        waterTextField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        colorPanel = new javax.swing.JPanel();
        colorButton = new javax.swing.JButton();
        opaqueLabel = new javax.swing.JLabel();
        opaqueSlider = new javax.swing.JSlider();
        sizeLabel = new javax.swing.JLabel();
        sizeSlider = new javax.swing.JSlider();
        angleLabel = new javax.swing.JLabel();
        clockwiseRadioButton = new javax.swing.JRadioButton();
        counterClockwiseRadioButton = new javax.swing.JRadioButton();
        angleSpinner = new javax.swing.JSpinner();
        alignLabel = new javax.swing.JLabel();
        alignPanel = new javax.swing.JPanel();
        paperAlignPanel = new javax.swing.JPanel();
        paperPointPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLeftRadioButton = new javax.swing.JRadioButton();
        topCenterPanel = new javax.swing.JPanel();
        topRadioButton = new javax.swing.JRadioButton();
        topRightRadioButton = new javax.swing.JRadioButton();
        leftRadioButton = new javax.swing.JRadioButton();
        centerPanel = new javax.swing.JPanel();
        centerRadioButton = new javax.swing.JRadioButton();
        rightRadioButton = new javax.swing.JRadioButton();
        bottomPanel = new javax.swing.JPanel();
        bottomLeftRadioButton = new javax.swing.JRadioButton();
        bottomCenterPanel = new javax.swing.JPanel();
        bottomRadioButton = new javax.swing.JRadioButton();
        bottomRightRadioButton = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        addLabel.setText("添加：");

        yesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        waterButtonGroup.add(yesRadioButton);
        yesRadioButton.setText("是");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        waterButtonGroup.add(noRadioButton);
        noRadioButton.setSelected(true);
        noRadioButton.setText("否");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        waterLabel.setText("水印：");

        waterTextField.setColumns(30);
        waterTextField.setText("watermark");

        colorLabel.setText("颜色：");

        colorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        colorPanel.setPreferredSize(new java.awt.Dimension(90, 22));
        colorPanel.setLayout(null);

        colorButton.setText("...");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        opaqueLabel.setText("浓度：");

        opaqueSlider.setBackground(new java.awt.Color(255, 255, 255));
        opaqueSlider.setMajorTickSpacing(10);
        opaqueSlider.setMaximum(95);
        opaqueSlider.setMinimum(5);
        opaqueSlider.setMinorTickSpacing(5);
        opaqueSlider.setPaintTicks(true);
        opaqueSlider.setSnapToTicks(true);
        opaqueSlider.setValue(45);

        sizeLabel.setText("尺寸：");

        sizeSlider.setBackground(new java.awt.Color(255, 255, 255));
        sizeSlider.setMajorTickSpacing(10);
        sizeSlider.setMaximum(95);
        sizeSlider.setMinimum(5);
        sizeSlider.setMinorTickSpacing(5);
        sizeSlider.setPaintTicks(true);
        sizeSlider.setSnapToTicks(true);
        sizeSlider.setValue(45);

        angleLabel.setText("角度：");

        clockwiseRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        pieButtonGroup.add(clockwiseRadioButton);
        clockwiseRadioButton.setText("顺时针");

        counterClockwiseRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        pieButtonGroup.add(counterClockwiseRadioButton);
        counterClockwiseRadioButton.setSelected(true);
        counterClockwiseRadioButton.setText("逆时针");

        angleSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 180, 15));
        NumberEditor editor = (NumberEditor) angleSpinner.getEditor();
        JFormattedTextField textField = editor.getTextField();
        NumberFormatter formatter = (NumberFormatter) textField.getFormatter();
        formatter.setFormat(new DecimalFormat("0°"));
        angleSpinner.setValue(45);

        alignLabel.setText("位置：");

        alignPanel.setBackground(new java.awt.Color(255, 255, 255));
        alignPanel.setLayout(new java.awt.BorderLayout());

        paperAlignPanel.setBackground(new java.awt.Color(255, 255, 255));
        paperAlignPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        paperPointPanel.setBackground(new java.awt.Color(255, 255, 255));
        paperPointPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paperPointPanel.setPreferredSize(new java.awt.Dimension(110, 150));
        paperPointPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setLayout(new java.awt.BorderLayout());

        topLeftRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(topLeftRadioButton);
        topLeftRadioButton.setName("1"); // NOI18N
        topPanel.add(topLeftRadioButton, java.awt.BorderLayout.WEST);

        topCenterPanel.setBackground(new java.awt.Color(255, 255, 255));

        topRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(topRadioButton);
        topRadioButton.setName("2"); // NOI18N
        topCenterPanel.add(topRadioButton);

        topPanel.add(topCenterPanel, java.awt.BorderLayout.CENTER);

        topRightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(topRightRadioButton);
        topRightRadioButton.setName("3"); // NOI18N
        topPanel.add(topRightRadioButton, java.awt.BorderLayout.EAST);

        paperPointPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        leftRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(leftRadioButton);
        leftRadioButton.setName("4"); // NOI18N
        paperPointPanel.add(leftRadioButton, java.awt.BorderLayout.LINE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        centerRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(centerRadioButton);
        centerRadioButton.setName("5"); // NOI18N
        centerPanel.add(centerRadioButton, new java.awt.GridBagConstraints());

        paperPointPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        rightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(rightRadioButton);
        rightRadioButton.setName("6"); // NOI18N
        paperPointPanel.add(rightRadioButton, java.awt.BorderLayout.LINE_END);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setLayout(new java.awt.BorderLayout());

        bottomLeftRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(bottomLeftRadioButton);
        bottomLeftRadioButton.setName("7"); // NOI18N
        bottomPanel.add(bottomLeftRadioButton, java.awt.BorderLayout.WEST);

        bottomCenterPanel.setBackground(new java.awt.Color(255, 255, 255));

        bottomRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(bottomRadioButton);
        bottomRadioButton.setName("8"); // NOI18N
        bottomCenterPanel.add(bottomRadioButton);

        bottomPanel.add(bottomCenterPanel, java.awt.BorderLayout.CENTER);

        bottomRightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        areaButtonGroup.add(bottomRightRadioButton);
        bottomRightRadioButton.setSelected(true);
        bottomRightRadioButton.setName("9"); // NOI18N
        bottomPanel.add(bottomRightRadioButton, java.awt.BorderLayout.EAST);

        paperPointPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        paperAlignPanel.add(paperPointPanel);

        alignPanel.add(paperAlignPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesRadioButton)
                        .addGap(30, 30, 30)
                        .addComponent(noRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opaqueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opaqueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(angleLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clockwiseRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(counterClockwiseRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(angleSpinner))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(alignLabel)
                            .addGap(10, 10, 10)
                            .addComponent(alignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLabel)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterLabel)
                    .addComponent(waterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(colorButton)
                        .addComponent(colorLabel))
                    .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opaqueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opaqueLabel)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sizeLabel)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockwiseRadioButton)
                    .addComponent(angleLabel)
                    .addComponent(counterClockwiseRadioButton)
                    .addComponent(angleSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alignLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

private void addRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    boolean enabled = (yesRadioButton.isSelected() ? true : false);
    waterLabel.setEnabled(enabled);
    waterTextField.setEnabled(enabled);
    colorLabel.setEnabled(enabled);
    colorButton.setEnabled(enabled);
    opaqueLabel.setEnabled(enabled);
    opaqueSlider.setEnabled(enabled);
    sizeLabel.setEnabled(enabled);
    sizeSlider.setEnabled(enabled);
    angleLabel.setEnabled(enabled);
    clockwiseRadioButton.setEnabled(enabled);
    counterClockwiseRadioButton.setEnabled(enabled);
    angleSpinner.setEnabled(enabled);
    alignLabel.setEnabled(enabled);
    topLeftRadioButton.setEnabled(enabled);
    topRadioButton.setEnabled(enabled);
    topRightRadioButton.setEnabled(enabled);
    leftRadioButton.setEnabled(enabled);
    centerRadioButton.setEnabled(enabled);
    rightRadioButton.setEnabled(enabled);
    bottomLeftRadioButton.setEnabled(enabled);
    bottomRadioButton.setEnabled(enabled);
    bottomRightRadioButton.setEnabled(enabled);
}                                              

private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
    Color selectedColor = JColorChooser.showDialog(this.getRootPane(), // 依靠的组件
            "水印颜色", // 对话框标题
            colorPanel.getBackground());// 颜色选择器的默认颜色

    if (selectedColor != null) {// 单击了“确定”按钮

        colorPanel.setBackground(selectedColor);// 修改面板的背景色

    }
}                                           

    // Variables declaration - do not modify                     
    private javax.swing.JLabel addLabel;
    private javax.swing.JLabel alignLabel;
    private javax.swing.JPanel alignPanel;
    private javax.swing.JLabel angleLabel;
    private javax.swing.JSpinner angleSpinner;
    private javax.swing.ButtonGroup areaButtonGroup;
    private javax.swing.JPanel bottomCenterPanel;
    private javax.swing.JRadioButton bottomLeftRadioButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JRadioButton bottomRadioButton;
    private javax.swing.JRadioButton bottomRightRadioButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JRadioButton centerRadioButton;
    private javax.swing.JRadioButton clockwiseRadioButton;
    private javax.swing.JButton colorButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JRadioButton counterClockwiseRadioButton;
    private javax.swing.JRadioButton leftRadioButton;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JLabel opaqueLabel;
    private javax.swing.JSlider opaqueSlider;
    private javax.swing.JPanel paperAlignPanel;
    private javax.swing.JPanel paperPointPanel;
    private javax.swing.ButtonGroup pieButtonGroup;
    private javax.swing.JRadioButton rightRadioButton;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JSlider sizeSlider;
    private javax.swing.JPanel topCenterPanel;
    private javax.swing.JRadioButton topLeftRadioButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JRadioButton topRadioButton;
    private javax.swing.JRadioButton topRightRadioButton;
    private javax.swing.ButtonGroup waterButtonGroup;
    private javax.swing.JLabel waterLabel;
    private javax.swing.JTextField waterTextField;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration                   

    public int getAngle() {
        return (Integer) angleSpinner.getValue();
    }

    public java.util.Enumeration getAreaEnumeration() {
        return areaButtonGroup.getElements();
    }

    public boolean isClockwiseRadioButtonSelected() {
        return clockwiseRadioButton.isSelected();
    }

    public java.awt.Color getColor() {
        return colorPanel.getBackground();
    }

    public int getOpaqueSliderValue() {
        return opaqueSlider.getValue();
    }

    public int getSizeSliderValue() {
        return sizeSlider.getValue();
    }

    public String getWatermark() {
        return waterTextField.getText();
    }

    public boolean isYesRadioButtonSelected() {
        return yesRadioButton.isSelected();
    }
}
